name: Rust CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Check formatting
        run: cargo fmt -- --check

      - name: Run Clippy
        run: cargo clippy --all-targets --all-features -- -A unused_variables -A clippy::approx_constant

      - name: Check project
        run: cargo check --workspace

      - name: Check examples
        run: cargo check --examples

      - name: Run tests
        run: cargo test --workspace